### ISSUE TITLE
Data Name Character Limit Applies in C Headers

### ISSUE THREAD

**Issue by KingDubDub** [mateoconlechuga/convbin#10]
Using the "-n" argument to input a name in convbin, the name is limited to 8 characters for the appvar in all output formats. This means that even if one passes "-oformat C" and creates a C header file that has no such character limitations, the array name is still subject to the character limit mean for appvars. So the input name "menu_room_tilemap" is converted to "menu_roo" and doesn't throw up any errors or warnings about the name size.

**Comment by KingDubDub** [comment]
The patch for #10 seems to have broken something else, all projects built with the new convbin fail to build after linking with: "C:\CEdev\bin\convbin.exe: unrecognised option `--uppercase' "
Afterwards it returns convbin -h and "make: *** [bin/DEMO.8xp] Error 1". Reverting back to the older version of convbin works fine.

**Comment by mateoconlechuga** [comment]
You are using the wrong release version.

**Comment by KingDubDub** [comment]
Just checked, I was somehow using version 3.0, not 3.4. Thanks for the help!
