### ISSUE TITLE
[Feature] .8xg => Contained Variable Conversion

### ISSUE THREAD

**Issue by acagliano** [mateoconlechuga/convbin#13]
Implement conversion from .8xg (auto-extracting/or non-auto-extraction) to unpacked contained variables.
Reasoning: the software can already convert TO groups of either type, may be useful to be able to convert FROM them as well.
I have a few use cases for this in mind myself.

**Comment by mateoconlechuga** [comment]
No.

**Comment by mateoconlechuga** [comment]
Fine maybe

**Comment by mateoconlechuga** [comment]
No.
