### ISSUE TITLE
Binary structure of 8XG files - do you know what the bytes represent?

### ISSUE THREAD

**Issue by SimonEast** [mateoconlechuga/convbin#18]
Hi there,

Thanks for sharing your application. This is not an issue, but more of a question. I'd like to understand the binary structure of 8XG files. I can parse 90% of it based on material I've found online, however I'm not sure about a few of the bytes.

I know that an 8XG group file contains:

* 55 byte header
* 19 byte meta data section
* variable length body
* 2 byte checksum

Then inside the body section there can be one or more variables or programs, where each contains:

* 1 byte representing the type of variable (5 for programs)
* **5 unknown bytes, where typically the first and last are 0x00** 👈
* 1 byte length of name/label
* the name
* 2 byte length of data

Could you happen to shed any light on what those 5 unknown bytes are for? I can't seem to determine any clear meaning for them.

Here's a screenshot of my parser in [Kaitai IDE](https://ide.kaitai.io/), which shows a simple 8XG file containing three very small sample programs. Each only a few bytes long.

![Screenshot](https://user-images.githubusercontent.com/813734/236666884-a0671994-c13d-4b1a-bddb-6fb984383344.jpg)

I tried to look through your C code, but I'm not quite clear on how it all works.

Cheers,

Simon

**Comment by adriweb** [comment]
Here's a parsing of your file ; doesn't look like you're missing much (or missing out on much, either)
BTW, real 8xg files like this aren't very common (edit: a program to specifically manage parse and manage them is [GFM](https://github.com/debrouxl/tilp_and_gfm/tree/master/gfm/trunk)), if you want to take a look at the 8xp/8xv file format, there are [docs](http://merthsoft.com/linkguide/ti83+/vars.html) [and](https://github.com/adriweb/imhex_ti8x) [multiple](https://github.com/adriweb/tivars_lib_cpp) [tools](https://github.com/TI-Toolkit/tivars_lib_py) [already](https://gitlab.com/taricorp/tifiles-rs).

<img width="600" alt="image" src="https://user-images.githubusercontent.com/660896/236668691-adb422f6-d581-4bd6-9439-112b1297a3c5.png">

**Comment by SimonEast** [comment]
Wow, thanks so much for this. Which hex editor did you use to generate this?

And what does the "Structure pointer" field actually refer to? Is that some kind of offset within the file or something? I'd like to know how to correctly generate that field.

Anyway, perhaps I can use your command line app to correctly generate an 8XG from multiple 8XP files, and not have to worry about creating my own compilation script. 🤔

And thanks for the links. I've come across some of them, but will take a deeper look.

**Comment by adriweb** [comment]
Well that's the output of a yet-unreleased plugin (for [HexFiend](https://hexfiend.com/)) by @LogicalJoe actually :P

The pointer is probably something internal to the calc referring to its address on the VAT on the calc? I'm not sure.

But anyway, there are two "types" of group files... real ones that show up as groups on-calc, which are rarely used nowadays, and ones with simply multiple variable entries in a row - they'll get auto-split by TI Connect CE for instance, and sent as individual variables to the calc. For instance, it's how [clibs.8xg](https://github.com/CE-Programming/libraries/releases/latest) is, actually.
My imHex plugin linked above supports this since not too long ago, if you want to dissect that to take a look.

**Comment by SimonEast** [comment]
OK, thanks for the tip.

I regularly use 5-10 8XP programs on my calculator for work, and I'm basically looking for a convenient way to package them on my PC after every update, to not only send them to the calculator, but to also keep backup copies in the archive so if I ever experience a RAM reset, I can get the applications back very easily.

So I probably want the option where they remain as a group on the calculator, in that case. 

Anyway, thanks for the suggestions. They'll be helpful.

**Comment by adriweb** [comment]
You say "use", does that mean just executing them? Or editing them too? If it's just using without editing, I suggest you just put them in archive instead of RAM, so that a RAM reset won't affect them, and since OS 5.3 you can run archived programs directly.

**Comment by LogicalJoe** [comment]
Author of the program in the screenshot above, just adding a quick note: the "Structure Pointer" is not read from in the group file; its value is a leftover from the internal VAT structure on the calculator and would point to the variable data in memory (which in the group is directly following the table entry).

Anyway, I highly recommend using [GFM](https://github.com/debrouxl/tilp_and_gfm/tree/master/gfm/trunk) for group management.
