### ISSUE TITLE
Assign appvar to app

### ISSUE THREAD

**Issue by Anonymous3-a** [mateoconlechuga/convbin#19]
I want to program in python from my computer and upload it to my calculator (TI-84+CE Python), but right now this is my method:

 - Get computer file size
 - Write that many bytes into file on calculator
 - Download file from calculator
 - Copy headers and footers from calculator file to computer file
 - Upload computer file to calculator

I'd rather be able to:

 - Convert computer file to 8Xv that is assigned to python app
 - Upload file

But convbin seems to not support assigning an appvar to a program, which is the way python tells what files are python files and not.
(By the way, I'm not sure what assigning an appvar to a program is technically called, so maybe it's just a misunderstanding)

**Comment by adriweb** [comment]
If you can't use TI Connect CE directly (which can transparently make the 8xv out of a .py script), you can use tivars_lib_py or tivars_lib_cpp to convert it.

That said, it's a [simple appvar format](https://github.com/adriweb/tivars_lib_cpp/blob/f627164d42e1b8757e70b12c8d8c7913a4496cf0/src/TypeHandlers/STH_PythonAppVar.cpp#L36) as it's mostly just the text with a few Python-appvar-specific metadata in a header before that. Maybe convbin could directly support it at some point.

**Comment by Anonymous3-a** [comment]
I have to use TiLP for calculator connection (because I run Linux).

Thanks for the advice though, I'll try that. If it works, I'll close the comment.

**Comment by Anonymous3-a** [comment]
It works, thank you!
