### ISSUE TITLE
Exporting larger than 64kB

### ISSUE THREAD

**Issue by mateoconlechuga** [mateoconlechuga/convbin#3]
This would entail splitting a large input file into multiple appvars; which the main program would then combine into a singular entity.

**Comment by mateoconlechuga** [comment]
Didn't I do this lol

**Comment by adriweb** [comment]
Well, I guess convbin dropped that feature :( Are you able to add it back?
I'd need this for lua, and someone else needs that too: https://tiplanet.org/forum/viewtopic.php?f=12&t=23915

Thanks :)

For reference, here's what the old code looked like: https://github.com/mateoconlechuga/convbin/blob/aa7fe580ed7e930f25a90fe4e0637a97b3b33100/main.c#L657-L721

**Comment by mateoconlechuga** [comment]
added with 961c2e36
